name: NodeJS with Webpack

on:
  push:
    branches: ['midas']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build, tag, and push image to Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_REPOSITORY: midas-ohif-viewer
          COMMIT_SHA: ${{ github.sha }}
        run: |
          IMAGE_TAG=${COMMIT_SHA::7}
          docker build -t $DOCKER_HUB_USERNAME/$DOCKER_HUB_REPOSITORY:central-$IMAGE_TAG -f platform/app/.recipes/Midas/dockerfile-central .
          docker push $DOCKER_HUB_USERNAME/$DOCKER_HUB_REPOSITORY:central-$IMAGE_TAG
          docker build -t $DOCKER_HUB_USERNAME/$DOCKER_HUB_REPOSITORY:hub-$IMAGE_TAG -f platform/app/.recipes/Midas/dockerfile-hub .
          docker push $DOCKER_HUB_USERNAME/$DOCKER_HUB_REPOSITORY:hub-$IMAGE_TAG
          docker build -t $DOCKER_HUB_USERNAME/$DOCKER_HUB_REPOSITORY:contributor-prod-$IMAGE_TAG -f platform/app/.recipes/Midas/dockerfile-contributor-prod .
          docker push $DOCKER_HUB_USERNAME/$DOCKER_HUB_REPOSITORY:contributor-prod-$IMAGE_TAG
